name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Using PostgreSQL
      uses: harmon758/postgresql-action@v1
      with:
        postgresql version: '12'  # See https://hub.docker.com/_/postgres for available versions
        postgresql db: 'abet_system_dev'
        postgresql password: 'waluigitime'
        postgresql user: 'postgres'

    - name: Checking out most recent version of code
      uses: actions/checkout@v1
      
    - name: Using Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
        
    - name: Clean npm install
      run: npm ci

    
    - name: setup Database
      run: npm setup_db:unix

    - name: Start the system
      run: npm start:unix

    - name: Run tests
      run: npm test:unix
